### PR TITLE
fix(dnsserver): allow view server blocks in any declaration order

### LINKED ISSUE #7733: Coredns fails to start when using same zone/port and filtering if the last server block is not the unfiltered one
**What happened**:

When two (or more) server blocks use the same zone and port with filtering based on the `view` plugin, if the unfiltered server block is not declared last, coredns raises the following error: `cannot serve dns://.:53 on 0.0.0.0 - it is already defined`.  In the examples available in [the view plugin documentation](https://coredns.io/plugins/view/), the unfiltered block is always in the last position, but nowhere is it mentioned that this is a mandatory condition.

Based on the multiple tests I did, this behavior seems to depend solely on the server blocks declaration order and not on:
- filtering expression or combination of filtering expressions (`type()`, `incidr(client_ip(), ...)`) .
- port used
- bind value (`0.0.0.0`, `127.0.0.1`, `lo`, ...)

✅ Example of a non failing configuration (unfiltered server block is the last one):
```
.:53 {
  bind 0.0.0.0
  view test_name_filter {
    expr name() contains 'github.com'
  }
  forward . 1.1.1.1
}

.:53 {
  bind 0.0.0.0
  forward . 1.1.1.1
}
```

❌ First example of a failing configuration (unfiltered server block is the first one):

```
.:53 {
  bind 0.0.0.0
  forward . 1.1.1.1
}

.:53 {
  bind 0.0.0.0
  view test_name_filter {
    expr name() contains 'github.com'
  }
  forward . 1.1.1.1
}
```

❌ Second example of a failing configuration (unfiltered server block is in the middle, so, it's not the last one):
```
.:53 {
  bind 0.0.0.0
  view test_name_filter_1 {
    expr name() contains 'github.com'
  }
  forward . 1.1.1.1
}

.:53 {
  bind 0.0.0.0
  forward . 1.1.1.1
}

.:53 {
  bind 0.0.0.0
  view test_name_filter_2 {
    expr name() contains 'kubernetes.io'
  }
  forward . 1.1.1.1
}
```

**What you expected to happen**:
Coredns should not behave differently depending on the server blocks declaration order, or if it is not a bug, [the view plugin documentation](https://coredns.io/plugins/view/) should mention that the unfiltered server block must be declared last.

**Environment**:
Reproduced on debian virtual machine (coredns 1.13.1) and also in a managed kubernetes (coredns 1.12.4).

### PR DESCRIPTION
**Pull request by umut-polat**
When using the view plugin, filtered and unfiltered server blocks can share the same zone and port. The zone overlap validation rejected this when the unfiltered block was not declared last because filtered configs treated an already-registered zone as an error.

The fix: for configs with filter functions (e.g. `view` plugin), skip the "already defined" check since they're expected to coexist with an unfiltered catch-all block on the same zone/port.

### What changed
- `core/dnsserver/register.go`: discard `existZone` for filtered configs in `validateZonesAndListeningAddresses`
- `test/view_test.go`: add `TestViewServerBlockOrdering` covering unfiltered-first and unfiltered-middle orderings

### Repro (before fix)
```
.:53 {
  forward . 1.1.1.1
}
.:53 {
  view test {
    expr name() contains 'github.com'
  }
  forward . 1.1.1.1
}
```
```
cannot serve dns://.:53 on 0.0.0.0 - it is already defined
```

Fixes #7733

### CODE REVIEW

File: test/view_test.go
Comment (thevilledev) [inline test/view_test.go:1]: The existing `viewTest` helper and the group in `TestView` already cover query routing. I think we need to reuse it here to verify routing actually works in the new orderings, not just startup.

**Review by thevilledev — CHANGES_REQUESTED** [review]
Hey @umut-polat, thank you for the contribution! I think the approach is solid, just needs tests.

File: test/view_test.go
Comment (umut-polat) [reply test/view_test.go:1]: good point - rewrote the test. it now spins up three orderings (filtered-first, unfiltered-first, unfiltered-middle) and uses `viewTest` to verify query routing in each case. pushed.

File: test/view_test.go [hunk 1]
```diff
@@ -162,3 +162,128 @@ func viewTest(t *testing.T, testName, addr, qname string, qtype uint16, expectRc
...
+	if err != nil {
+		t.Fatalf("Expected server to start with unfiltered-middle ordering, but got error: %s", err)
+	}
+	defer i3.Stop()
+
+	// A is matched by view v1 (first block) -> 1.2.3.4
+	viewTest(t, "unfiltered-middle A", addr3, "test.order-test3.", dns.TypeA, dns.RcodeSuccess,
+		[]dns.RR{test.A("test.order-test3.	303	IN	A	1.2.3.4")})
+	// MX is not matched by any view, falls through to unfiltered -> 5.6.7.8 (hosts returns A)
+	// AAAA after unfiltered is unreachable (unfiltered catches it first)
```
Comment (thevilledev) [inline test/view_test.go]: A few things:

1. The comment describes routing behavior but there are no assertions backing them up. Could you add those?

2. Even after this change the declaration order still affects routing. I think the PR description reads as if the ordering problem is fully solved.

3. Looking at the `view` plugin README ([link](https://coredns.io/plugins/view/)) we can see that all examples always have an unfiltered catch-all as the last block. Nothing says that it's a requirement. Since this PR is trying to fix this confusion, could you also update the README? I think a short note in the Description or Examples section is warranted.

File: test/view_test.go
Comment (umut-polat) [reply test/view_test.go:1]: updated:

1. added routing assertions for all three orderings - each subtest now verifies queries go to the expected block via `viewTest`
2. clarified in the PR description that this only fixes the startup validation, not routing order
3. added a "Server Block Ordering" section to `plugin/view/README.md` documenting the top-to-bottom evaluation

**Review by thevilledev — APPROVED** [review]
Please fix the linting, other than that LGTM. Thanks @umut-polat.

**Comment by Jamal-B** [comment]
@umut-polat Thank you for the fix and the Readme update!
