### PR TITLE
plugin/kubernetes: fix headless/endpoint query panics when endpoints are disabled

### LINKED ISSUE #6087: Plugin kubernetes panics if noendpoints is set and it received a request for a headless service
**What happened**:
Plugin `kubernetes` panics in `kubernetes.(*dnsControl).EpIndex` if `noendpoints` is set and it receives a request for a headless service.

**What you expected to happen**:
It should return `NXDOMAIN` as [documented](https://coredns.io/plugins/kubernetes/).

**How to reproduce it (as minimally and precisely as possible)**:

Start CoreDNS with `kubernetes` plugin enabled and `noendpoints` set.

Create a headless service in kubernetes, e.g. foo in default namespace.

`dig @10.96.0.10 foo.default.svc.cluster.local.`

CoreDNS returns `SERVFAIL` and logs a panic message.

**Anything else we need to know?**:

It seems PR [#2128](https://github.com/coredns/coredns/pull/2128) removes a lot of is-nil checks. Any special considerations?

**Environment**:

- the version of CoreDNS: v1.10.1
- Corefile:
```
...
  errors
  kubernetes ... {
    noendpoints
    ttl 30
    fallthrough
  }
...
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others: k8s v1.26.4

### PR DESCRIPTION
**Pull request by chrisohaver**
### 1. Why is this pull request needed and what does it do?

Fixes headless and endpoint query panics when endpoints are disabled. This fix always creates listers for all objects, even when an object such as Endpoints is disabled. This way, the listers are never nil, and we don't have to check them every time before accessing them. However, when endpoints is disabled, the _controller_ is not started, so the lister remains completely empty (no items in it and empty indexes).

This PR also fixes tests and fixtures in controller_test.go, which were broken in many ways, rendering the existing benchmark therein somewhat meaningless.  Fixing the existing test was necessary to get the new tests to work.

- API controllers were never started during the test, so the lister stores and indexes were never filled with the test data. The benchmark has been running on an empty set of data, receiving NXDOMAIN for everything. - fixed by starting the controller. 
- Endpoint test data were created as Endpoints, but controller defaults to watch EndpointSlices, so even once the test was fixed to start the controller, it was not seeing the endpoints created - fixed by updating them to be created as EndpointSlices.
- the created service names and endpoint service names were mismatched, creating dangling endpoints with non-existent services - fixed by making all service names consistent 

### 2. Which issues (if any) are related?

fixes #6087

### CODE REVIEW

File: plugin/kubernetes/controller_test.go [hunk 1]
```diff
@@ -25,62 +28,122 @@ func inc(ip net.IP) {
...
 
 	// Add resources
-	generateEndpoints(cidr, client)
-	generateSvcs(cidr, "all", client)
-	m := new(dns.Msg)
-	m.SetQuestion("svc1.testns.svc.cluster.local.", dns.TypeA)
+	_, err := client.CoreV1().Namespaces().Create(ctx, &api.Namespace{ObjectMeta: meta.ObjectMeta{Name: "testns"}}, meta.CreateOptions{})
+	if err != nil {
+		println(err.Error())
+		log.Fatal(err)
```
Comment (Tantalor93) [inline plugin/kubernetes/controller_test.go]: why this double logging? I would just keep `log.Fatal(err)` and remove the other

File: plugin/kubernetes/controller_test.go [hunk 2]
```diff
@@ -25,62 +28,122 @@ func inc(ip net.IP) {
...
+func TestEndpointsDisabled(t *testing.T) {
+	ctx := context.Background()
+	k := kubernertesWithFakeClient(ctx, "cluster.local.", "10.0.0.0/30", false, "headless")
+	k.opts.initEndpointsCache = false
+
+	go k.APIConn.Run()
+	for !k.APIConn.HasSynced() {
+		time.Sleep(time.Millisecond)
+	}
+
```
Comment (Tantalor93) [inline plugin/kubernetes/controller_test.go:81]: `defer k.APIConn.Stop()`
to avoid running wild goroutine after the test is done?

File: plugin/kubernetes/controller_test.go [hunk 3]
```diff
@@ -25,62 +28,122 @@ func inc(ip net.IP) {
...
+func TestEndpointsEnabled(t *testing.T) {
+	ctx := context.Background()
+	k := kubernertesWithFakeClient(ctx, "cluster.local.", "10.0.0.0/30", true, "headless")
+	k.opts.initEndpointsCache = true
+
+	go k.APIConn.Run()
+	for !k.APIConn.HasSynced() {
+		time.Sleep(time.Millisecond)
+	}
+
```
Comment (Tantalor93) [inline plugin/kubernetes/controller_test.go:101]:
```suggestion
	defer k.APIConn.Stop()
```

File: plugin/kubernetes/controller_test.go [hunk 4]
```diff
@@ -25,62 +28,122 @@ func inc(ip net.IP) {
...
+func BenchmarkController(b *testing.B) {
+	ctx := context.Background()
+	k := kubernertesWithFakeClient(ctx, "cluster.local.", "10.0.0.0/24", true, "all")
+
+	go k.APIConn.Run()
+	for !k.APIConn.HasSynced() {
+		time.Sleep(time.Millisecond)
+	}
+
```
Comment (Tantalor93) [inline plugin/kubernetes/controller_test.go:60]:
```suggestion
	defer k.APIConn.Stop()

```

File: plugin/kubernetes/controller_test.go [hunk 5]
```diff
@@ -25,62 +28,122 @@ func inc(ip net.IP) {
 	}
 }
 
-func BenchmarkController(b *testing.B) {
+func kubernertesWithFakeClient(ctx context.Context, zone, cidr string, initEndpointsCache bool, svcType string) *Kubernetes {
```
Comment (Tantalor93) [inline plugin/kubernetes/controller_test.go]: typo
```suggestion
func kubernetesWithFakeClient(ctx context.Context, zone, cidr string, initEndpointsCache bool, svcType string) *Kubernetes {
```

File: plugin/kubernetes/controller_test.go (hunk 1 above)
Comment (chrisohaver) [reply plugin/kubernetes/controller_test.go]: stray debug.  will remove.

**Review by Tantalor93 — APPROVED** [review]

File: plugin/kubernetes/controller.go [hunk 6]
```diff
@@ -128,33 +128,37 @@ func newdnsController(ctx context.Context, kubeClient kubernetes.Interface, opts
...
+		&cache.ListWatch{
+			ListFunc:  endpointSliceListFunc(ctx, dns.client, api.NamespaceAll, dns.selector),
+			WatchFunc: endpointSliceWatchFunc(ctx, dns.client, api.NamespaceAll, dns.selector),
+		},
+		&discovery.EndpointSlice{},
+		cache.ResourceEventHandlerFuncs{AddFunc: dns.Add, UpdateFunc: dns.Update, DeleteFunc: dns.Delete},
+		cache.Indexers{epNameNamespaceIndex: epNameNamespaceIndexFunc, epIPIndex: epIPIndexFunc},
+		object.DefaultProcessor(object.EndpointSliceToEndpoints, dns.EndpointSliceLatencyRecorder()),
+	)
+	dns.epLock.Lock()
```
Comment (bradbeam) [inline plugin/kubernetes/controller.go:156]: this lock seems unnecessary. is there a reason we are doing it that I'm missing?

**Review by bradbeam — APPROVED** [review]

File: plugin/kubernetes/controller.go (hunk 6 above)
Comment (chrisohaver) [reply plugin/kubernetes/controller.go:156]: required for endpoints vs endpointslice watch selection.

Comment (chrisohaver) [reply plugin/kubernetes/controller.go:156]: > required for endpoints vs endpointslice watch selection.

the dynamic  endpoints/endpointslice detection can eventually go away when we no longer need to support k8s 1.19.0? IIRC? is that EOL yet?  maybe we can drop it now.

Comment (chrisohaver) [reply plugin/kubernetes/controller.go:156]: OK k8s 1.19 went EOL over a year ago, so I think we can move the endpoint watch code over to endpointslice only now... but not in this PR.

Comment (bradbeam) [reply plugin/kubernetes/controller.go:156]: Was more a question around the lock itself since dns gets created at the start of the function and I dont believe anything else has reference to it at this point.
But good find nonetheless :)

Comment (chrisohaver) [reply plugin/kubernetes/controller.go:156]: it is referenced elsewhere, during startup when determining which object to watch.

Comment (chrisohaver) [reply plugin/kubernetes/controller.go:156]: ah- I see what you mean. (yes - it could be removed from this spot)
