### PR TITLE
plugin/k8s_external: fix SRV queries doesn't work with AWS ELB/NLB

### LINKED ISSUE #4927: k8s_external plugin doesn't work with AWS ELB/NLB with query=SRV
## What happened
Steps to reproduce:

1. setup AWS ELB/NLB cluster 
2. override coredns config with adding `k8s_external my_cluster`
3. expose kube-dns service to public via `kubectl expose service kube-dns -n kube-system --port=53 --target-port=53 --protocol=TCP --name=exposed-kube-dns --type=LoadBalancer`
4. do lookup for SRV `_._tcp.exposed-kube-dns-service.kube-system.my_cluster`

**Actual: error 10.100.0.10:53: lame referral**

## What you expected to happen
 coredns responded  correctly 
 
 ## Anything else that we need to know
 
 1. It is not reproducing if force set `external-ip `for the service.
 2. IP address lookup is working correctly. 
  
## Environment

- the version of CoreDNS:
- Corefile:`coredns/coredns:1.8.4`

## Corefile

```
Name:         coredns
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
Corefile:
----
.:53 {
    errors
    health {
        lameduck 5s
    }
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
    }
    k8s_external my_cluster
    prometheus :9153
    forward . /etc/resolv.conf {
        max_concurrent 1000
    }
    loop
}
```

### PR DESCRIPTION
**Pull request by denis-tingaikin**
Signed-off-by: denis-tingaikin <denis.tingajkin@xored.com>

### 1. Why is this pull request needed and what does it do?

1. Fixes https://github.com/coredns/coredns/issues/4927
2. **Tested on AWS cluster**

### 2. Which issues (if any) are related?

https://github.com/coredns/coredns/issues/4927

### 3. Which documentation changes (if any) need to be made?

No documentation changes need to be made.

### 4. Does this introduce a backward incompatible change or deprecation?

This change does not introduce a backward-incompatible change of depreciation.

### 5. Comporation with  coredns/coredns:1.8.6

Corefile:
```
.:53 {
    errors
    health {
      lameduck 5s
    }
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . /etc/resolv.conf {
      max_concurrent 1000
    }
    k8s_external my.cluster
    loop
    reload
    loadbalance
}
```

k8s services:
```
NAMESPACE     NAME                TYPE           CLUSTER-IP      EXTERNAL-IP                                                               PORT(S)                  AGE
default       kubernetes          ClusterIP      10.100.0.1      <none>                                                                    443/TCP                  3h37m
kube-system   exposed-kube-dns2   LoadBalancer   10.100.57.201   a2fd497e947fe4cbfb99ea8a39525efb-1948346745.us-east-2.elb.amazonaws.com   53:32725/TCP             171m
kube-system   kube-dns            ClusterIP      10.100.0.10     <none>                                                                    53/UDP,53/TCP,9153/TCP   3h37m
```

Query: `dig  @18.216.219.94  _._tcp.exposed-kube-dns2.kube-system.my.cluster +tcp SRV`

**Response from coredns/coredns:1.8.6**
```
; <<>> DiG 9.10.6 <<>> @18.216.219.94 _._tcp.exposed-kube-dns2.kube-system.my.cluster +tcp SRV
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19182
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_._tcp.exposed-kube-dns2.kube-system.my.cluster. IN SRV

;; AUTHORITY SECTION:
my.cluster.		5	IN	SOA	ns1.dns.my.cluster. hostmaster.dns.my.cluster. 12345 7200 1800 86400 5

;; Query time: 7348 msec
;; SERVER: 18.216.219.94#53(18.216.219.94)
;; WHEN: Wed Oct 20 16:16:29 MSK 2021
;; MSG SIZE  r
```

**Updated: Response from coredns based on this patch:**

```
; <<>> DiG 9.10.6 <<>> @a5ae6cc6610dc4c8eb324396028858a3-368021828.us-east-2.elb.amazonaws.com. _._tcp.exposed-kube-dns2.kube-system.my.cluster +tcp SRV
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20326
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 3
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_._tcp.exposed-kube-dns2.kube-system.my.cluster. IN SRV

;; ANSWER SECTION:
_._tcp.exposed-kube-dns2.kube-system.my.cluster. 5 IN SRV 0 100 53 a5ae6cc6610dc4c8eb324396028858a3-368021828.us-east-2.elb.amazonaws.com.

;; ADDITIONAL SECTION:
a5ae6cc6610dc4c8eb324396028858a3-368021828.us-east-2.elb.amazonaws.com.	60 IN A	3.129.123.240
a5ae6cc6610dc4c8eb324396028858a3-368021828.us-east-2.elb.amazonaws.com.	60 IN A	18.117.198.240

;; Query time: 184 msec
;; SERVER: 3.129.123.240#53(3.129.123.240)
;; WHEN: Thu Oct 21 01:53:13 MSK 2021
;; MSG SIZE  rcvd: 385
```

### CODE REVIEW

**Comment by denis-tingaikin** [comment]
@chrisohaver  Could you please review this?

File: plugin/k8s_external/external_test.go [hunk 1]
```diff
@@ -153,6 +153,12 @@ var tests = []test.Case{
 			test.A("svc11.testns.example.com.	5	IN	A	1.2.3.4"),
 		},
 	},
+	{
+		Qname: "_http._tcp.svc12.testns.example.com.", Qtype: dns.TypeSRV, Rcode: dns.RcodeSuccess,
```
Comment (denis-tingaikin) [inline plugin/k8s_external/external_test.go:157]: Note: svc12.testns.example.com has hostname entry (no extrernal IP) see at https://github.com/coredns/coredns/blob/master/plugin/k8s_external/external_test.go#L219

So AWS ELB/NLB creates similar entries in k8s for exposed services.

**Comment by chrisohaver** [comment]
Strictly speaking, an SRV that targets an alias record (such as a CNAME) violates the SRV RFC...

https://datatracker.ietf.org/doc/html/rfc2782 : page 3
```
  Target
        The domain name of the target host.  There MUST be one or more
        address records for this name, the name MUST NOT be an alias (in
        the sense of RFC 1034 or RFC 2181).
```

I think the correct approach would be to collapse the result ... e.g. ...

```
dig  @18.216.219.94  _._tcp.exposed-kube-dns2.kube-system.my.cluster +tcp SRV

; <<>> DiG 9.10.6 <<>> @18.216.219.94 _._tcp.exposed-kube-dns2.kube-system.my.cluster +tcp SRV
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48404
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 4
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_._tcp.exposed-kube-dns2.kube-system.my.cluster. IN SRV

;; ANSWER SECTION:
_._tcp.exposed-kube-dns2.kube-system.my.cluster. 5 IN SRV 0 100 53 a2fd497e947fe4cbfb99ea8a39525efb-1948346745.us-east-2.elb.amazonaws.com.

;; ADDITIONAL SECTION:
a2fd497e947fe4cbfb99ea8a39525efb-1948346745.us-east-2.elb.amazonaws.com. 60 IN A 18.216.219.94
a2fd497e947fe4cbfb99ea8a39525efb-1948346745.us-east-2.elb.amazonaws.com. 60 IN A 3.19.43.103

;; Query time: 185 msec
;; SERVER: 18.216.219.94#53(18.216.219.94)
;; WHEN: Wed Oct 20 15:18:18 MSK 2021
;; MSG SIZE  rcvd: 482
```

**Review by chrisohaver — CHANGES_REQUESTED** [review]
Thanks!  Per https://github.com/coredns/coredns/pull/4929#issuecomment-947718708, please try collapsing the response so it does not contain a CNAME.

**Comment by denis-tingaikin** [comment]
> dig  @18.216.219.94  _._tcp.exposed-kube-dns2.kube-system.my.cluster +tcp SRV
> 
> ; <<>> DiG 9.10.6 <<>> @18.216.219.94 _._tcp.exposed-kube-dns2.kube-system.my.cluster +tcp SRV
> ; (1 server found)
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48404
> ;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 4
> ;; WARNING: recursion requested but not available
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;_._tcp.exposed-kube-dns2.kube-system.my.cluster. IN SRV
> 
> ;; ANSWER SECTION:
> _._tcp.exposed-kube-dns2.kube-system.my.cluster. 5 IN SRV 0 100 53 a2fd497e947fe4cbfb99ea8a39525efb-1948346745.us-east-2.elb.amazonaws.com.
> 
> ;; ADDITIONAL SECTION:
> a2fd497e947fe4cbfb99ea8a39525efb-1948346745.us-east-2.elb.amazonaws.com. 60 IN A 18.216.219.94
> a2fd497e947fe4cbfb99ea8a39525efb-1948346745.us-east-2.elb.amazonaws.com. 60 IN A 3.19.43.103
> 
> ;; Query time: 185 msec
> ;; SERVER: 18.216.219.94#53(18.216.219.94)
> ;; WHEN: Wed Oct 20 15:18:18 MSK 2021
> ;; MSG SIZE  rcvd: 482


As I can see in `cluster.local` kuberenetes SRV records look like

```
; <<>> DiG 9.11.6-P1 <<>> kubernetes +tcp +search SRV
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54670
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 2
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: d8ad1bb9a9a326f6 (echoed)
;; QUESTION SECTION:
;kubernetes.default.svc.cluster.local. IN SRV

;; ANSWER SECTION:
kubernetes.default.svc.cluster.local. 5	IN SRV	0 100 443 kubernetes.default.svc.cluster.local.

;; ADDITIONAL SECTION:
kubernetes.default.svc.cluster.local. 5	IN A	10.100.0.1

;; Query time: 0 msec
;; SERVER: 10.100.0.10#53(10.100.0.10)
;; WHEN: Wed Oct 20 15:08:04 UTC 2021
;; MSG SIZE  rcvd: 221
```

Should `k8s_external` be consistent with `kubernetees`? 

In this case, we only need to remove CNAME record.

For example:

```

dig  @18.216.219.94  _._tcp.exposed-kube-dns2.kube-system.my.cluster +tcp SRV

; <<>> DiG 9.10.6 <<>> @18.216.219.94 _._tcp.exposed-kube-dns2.kube-system.my.cluster +tcp SRV
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48404
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 4
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_._tcp.exposed-kube-dns2.kube-system.my.cluster. IN SRV

;; ANSWER SECTION:
_._tcp.exposed-kube-dns2.kube-system.my.cluster. 5 IN SRV 0 100 53 exposed-kube-dns2.kube-system.my.cluster.

;; ADDITIONAL SECTION:
a2fd497e947fe4cbfb99ea8a39525efb-1948346745.us-east-2.elb.amazonaws.com. 60 IN A 18.216.219.94
a2fd497e947fe4cbfb99ea8a39525efb-1948346745.us-east-2.elb.amazonaws.com. 60 IN A 3.19.43.103

;; Query time: 185 msec
;; SERVER: 18.216.219.94#53(18.216.219.94)
;; WHEN: Wed Oct 20 15:18:18 MSK 2021
;; MSG SIZE  rcvd: 482
```

**Comment by chrisohaver** [comment]
> Should k8s_external be consistent with kubernetees?
> In this case, we only need to remove CNAME record.

Not sure I understand? If you only remove the CNAME, then the SRV Target won't match any of the additional records names.

**Comment by denis-tingaikin** [comment]
@chrisohaver Finally got it! Ok, will do

**Comment by denis-tingaikin** [comment]
@chrisohaver  Done.

Now it responds this:

```
; <<>> DiG 9.10.6 <<>> @18.216.219.94 _._tcp.exposed-kube-dns2.kube-system.my.cluster +tcp SRV
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19331
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 3
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_._tcp.exposed-kube-dns2.kube-system.my.cluster. IN SRV

;; ANSWER SECTION:
_._tcp.exposed-kube-dns2.kube-system.my.cluster. 5 IN SRV 0 100 53 a2fd497e947fe4cbfb99ea8a39525efb-1948346745.us-east-2.elb.amazonaws.com.

;; ADDITIONAL SECTION:
a2fd497e947fe4cbfb99ea8a39525efb-1948346745.us-east-2.elb.amazonaws.com. 60 IN A 3.19.43.103
a2fd497e947fe4cbfb99ea8a39525efb-1948346745.us-east-2.elb.amazonaws.com. 60 IN A 18.216.219.94

;; Query time: 3248 msec
;; SERVER: 18.216.219.94#53(18.216.219.94)
;; WHEN: Wed Oct 20 18:36:08 MSK 2021
;; MSG SIZE  rcvd: 388

```

File: plugin/k8s_external/external_test.go [hunk 2]
```diff
@@ -153,6 +153,12 @@ var tests = []test.Case{
...
+		Answer: []dns.RR{
+			test.SRV("_http._tcp.svc12.testns.example.com.	5	IN	SRV	0 100 80 svc12.testns.example.com."),
+		},
```
Comment (chrisohaver) [inline plugin/k8s_external/external_test.go:160]: There should be an Extra/Additional section here that confirms the ~CNAME squashing~ new behavior.

(edit: it isn't really CNAME squashing)

File: plugin/k8s_external/msg_to_dns.go [hunk 3]
```diff
@@ -131,6 +125,19 @@ func (e *External) srv(services []msg.Service, state request.Request) (records,
 					extra = append(extra, &dns.A{Hdr: hdr, A: ip})
 				case dns.TypeAAAA:
 					extra = append(extra, &dns.AAAA{Hdr: hdr, AAAA: ip})
+				case dns.TypeCNAME:
+					resp, err := e.upstream.Lookup(ctx, state, dns.Fqdn(s.Host), dns.TypeA)
```
Comment (chrisohaver) [inline plugin/k8s_external/msg_to_dns.go]: Need to look up AAAA too ...

File: plugin/k8s_external/external_test.go (hunk 2 above)
Comment (denis-tingaikin) [reply plugin/k8s_external/external_test.go:160]: Note: we have no upstream server in these tests.

Comment (denis-tingaikin) [reply plugin/k8s_external/external_test.go:160]: so I can improve these tests and add the upstream server. 
Is it make sense?

File: plugin/k8s_external/msg_to_dns.go [hunk 4]
```diff
@@ -131,6 +125,19 @@ func (e *External) srv(services []msg.Service, state request.Request) (records,
...
+					if err != nil {
+						break
+					}
+					for index, answer := range resp.Answer {
```
Comment (chrisohaver) [inline plugin/k8s_external/msg_to_dns.go]: I don't think this CNAME stripping needs to be done. 
The important thing is that CoreDNS is not synthesizing a CNAME in addition the the SRV here.  IMO, we can assume the response from the lookup of the externalIP hostname will not have a CNAME in the answer.  If it does, it means the admin configured the service with a CNAME host into the externalIP field (garbage in garbage out). In fact, it would seem this code expects/requires that the lookup will include a CNAME in the response.

IOW, all we need to do is set the SRV Target to the hostname,  lookup A and AAAA records for the hostname, and add them to the Additional section.

If we decide we _do_ want to want to clean this kind of thing up for the user, then we should also handle squashing chains (CNAMEs that point to CNAMEs that point to CNAMEs, etc).

**Review by chrisohaver — CHANGES_REQUESTED** [review]

File: plugin/k8s_external/external_test.go (hunk 2 above)
Comment (chrisohaver) [reply plugin/k8s_external/external_test.go:160]: I think we can gat away with just verifying the SRV Target is correct.  If the externalIP is a hostname, then the target should be that hostname...  In this case, it's not, so the expectation is wrong, and if it's passing, the code is not working correctly.

File: plugin/k8s_external/msg_to_dns.go (hunk 4 above)
Comment (denis-tingaikin) [reply plugin/k8s_external/msg_to_dns.go]: I thought you specially removed CNAME entry here https://github.com/coredns/coredns/pull/4929#issuecomment-947718708

OK, will fix it, thanks for clarifications.

Comment (chrisohaver) [reply plugin/k8s_external/msg_to_dns.go]: Yeah - sorry, I incorrectly thought that the first commit was synthesizing the CNAME.  But I'm guessing you have specified a CNAME as the hostname in the example you gave?  That was a confusing example.

File: plugin/k8s_external/external_test.go (hunk 2 above)
Comment (denis-tingaikin) [reply plugin/k8s_external/external_test.go:160]: Yes, you are correct. Fixed.

File: plugin/k8s_external/msg_to_dns.go (hunk 3 above)
Comment (denis-tingaikin) [reply plugin/k8s_external/msg_to_dns.go]: Thanks, fixed.

File: plugin/k8s_external/msg_to_dns.go (hunk 4 above)
Comment (denis-tingaikin) [reply plugin/k8s_external/msg_to_dns.go]: All fine, fixed.

**Review by chrisohaver — APPROVED** [review]
LGTM Thanks!

**Comment by denis-tingaikin** [comment]
Tested on AWS all work as expected. I've updated the response from coredns based on this patch (see at https://github.com/coredns/coredns/pull/4929#issue-1031351299)

This also solves problems with our scenarios on AWS.

@miekg Could you have a look?
