### PR TITLE
plugin/kubernetes: error NXDOMAIN for TXT lookups

### LINKED ISSUE #5736: plugin/kubernetes should return an NXDOMAIN for missing TXT queries
**What happened**:
TXT queries are incorrectly returning with an empty NOERROR response rather than NXDOMAIN. Beyond just being incorrect this matters because as a valid response it means that DNS clients won't try additional domains in their search path to hopefully find the right thing.

**What you expected to happen**:
CoreDNS should return an NXDOMAIN as the record doesn't exist

**How to reproduce it (as minimally and precisely as possible)**:
```
[]$ export CLUSTERDOMAIN=prod.cluster.local
[]$ dig foobarbaz.svc.$CLUSTERDOMAIN TXT @192.168.240.10 | grep status
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45013
```

Expected:
```
[]$ dig foo.google.com TXT @8.8.8.8 | grep status
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 53366
```

**Anything else we need to know?**:
This works properly for SRV and A records (anything the Kubernetes plugin actually supports):
```
[]$ dig foo.svc.$CLUSTERDOMAIN SRV @192.168.240.10 | grep status
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 58698

[]$ dig foo.svc.$CLUSTERDOMAIN A @192.168.240.10 | grep status
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 10092
```

**Environment**:

- the version of CoreDNS: 1.9.1
- Corefile:
```
.:53 {
    log
    errors
    health
    ready
    kubernetes prod.cluster.local
    forward . 8.8.8.8
    prometheus :9153
    cache 10
    loop
    reload
    loadbalance
}

```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

### PR DESCRIPTION
**Pull request by LAMRobinson**
### 1. Why is this pull request needed and what does it do?
All non "dns-version" TXT queries should return a NXDOMAIN rather than NOERROR

### 2. Which issues (if any) are related?
#5736

### 4. Does this introduce a backward incompatible change or deprecation?

### CODE REVIEW

File: plugin/kubernetes/kubernetes.go [hunk 1]
```diff
@@ -102,10 +102,10 @@ func (k *Kubernetes) Services(ctx context.Context, state request.Request, exact
 
 		segs := dns.SplitDomainName(t)
 		if len(segs) != 1 {
-			return nil, nil
+			return nil, errInvalidRequest
```
Comment (chrisohaver) [inline plugin/kubernetes/kubernetes.go]: The answer should be the same as in the next `if`.
This and the following `if` can be combined into one.

File: plugin/kubernetes/kubernetes.go [hunk 2]
```diff
@@ -102,10 +102,10 @@ func (k *Kubernetes) Services(ctx context.Context, state request.Request, exact
...
 		}
 		if segs[0] != "dns-version" {
-			return nil, nil
+			return nil, errNoItems
```
Comment (chrisohaver) [inline plugin/kubernetes/kubernetes.go]: Strictly speaking, in the case that the TXT query is for a name that exists for another record type, the answer should be "NODATA".  This is expected DNS behavior.

So, before returning `errNoItems` (which results in NXDOMAIN), this code would need to check to see if a service with the name exists.  If one does exist, then the error returned should be `nil` (which results in NODATA).

**Review by chrisohaver — CHANGES_REQUESTED** [review]
Thanks! Comments in line. Please also add test cases.

File: plugin/kubernetes/kubernetes.go (hunk 2 above)
Comment (LAMRobinson) [reply plugin/kubernetes/kubernetes.go]: Good point - I've got this working:
```
$ dig foo.svc.prod.cluster.local TXT @192.168.240.10 | grep status
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 49658

$ dig kubernetes.default.svc.prod.cluster.local TXT @192.168.240.10 | grep status
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15694
```

**Review by chrisohaver — COMMENTED** [review]
Looks good.  Can you sign the commits?

File: plugin/kubernetes/kubernetes.go (hunk 1 above)
Comment (LAMRobinson) [reply plugin/kubernetes/kubernetes.go]: I ended up restructuring this a bit, rather than checking for a negative (make sure this isn't a query for "dns-version"), we now check if it is a query for "dns-version" and serve that if so, otherwise return NXDOMAIN

**Comment by LAMRobinson** [comment]
OK should be good to go, let me know !

```
$ dig kubernetes.default.svc.prod.cluster.local TXT @192.168.240.10 | grep status
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60508

$ dig foo.svc.prod.cluster.local TXT @192.168.240.10 | grep status
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 13919

$ dig dns-version.prod.cluster.local TXT @192.168.240.10 | grep version
; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.9 <<>> dns-version.prod.cluster.local TXT @10.229.2.32
; EDNS: version: 0, flags:; udp: 4096
;dns-version.prod.cluster.local.        IN      TXT
dns-version.prod.cluster.local. 10 IN   TXT     "1.1.0"
```

File: plugin/kubernetes/kubernetes.go [hunk 3]
```diff
@@ -110,7 +110,7 @@ func (k *Kubernetes) Services(ctx context.Context, state request.Request, exact
 
 		// Hard code the only valid TXT - "dns-version.<zone>"
```
Comment (chrisohaver) [inline plugin/kubernetes/kubernetes.go]: I think this check should happen before the `Records` check, so the more expensive Records check is only performed for TXT queries that do not match the static dns-version record.

**Review by chrisohaver — COMMENTED** [review]
Thanks. Please also fix the reviewdog whitespace notifications, imbedded in-line in Files Changed.

File: plugin/kubernetes/handler_test.go [hunk 4]
```diff
@@ -251,7 +251,9 @@ var dnsTestCases = []kubeTestCase{
 	{Case: test.Case{
 		Qname: "kubernetes.default.svc.cluster.local.", Qtype: dns.TypeTXT,
 		Rcode:  dns.RcodeSuccess,
-		Answer: []dns.RR{},
+		Answer: []dns.RR{
+			test.SOA("cluster.local.	5	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1499347823 7200 1800 86400 5"),
+        },
```
Comment (chrisohaver) [inline plugin/kubernetes/handler_test.go]: This doesn't look right.

For a NODATA response, the SOA record should be in the Authority section (`Ns`).

File: plugin/kubernetes/kubernetes.go (hunk 3 above)
Comment (LAMRobinson) [reply plugin/kubernetes/kubernetes.go]: good idea, done

File: plugin/kubernetes/handler_test.go (hunk 4 above)
Comment (LAMRobinson) [reply plugin/kubernetes/handler_test.go]: yeah I expected as such, but was trying to troubleshoot why a test was failing - ill revert

**Comment by LAMRobinson** [comment]
@chrisohaver can you give me a pointer for identifying this failing test? don't seem to be able to identify it in the source

```
--- FAIL: TestServeDNS (0.00s)
    handler_test.go:449: Test 24, rcode is "NXDOMAIN", expected "NOERROR"
FAIL
```

**Comment by chrisohaver** [comment]
> @chrisohaver can you give me a pointer for identifying this failing test? don't seem to be able to identify it in the source
> 
> ```
> --- FAIL: TestServeDNS (0.00s)
>     handler_test.go:449: Test 24, rcode is "NXDOMAIN", expected "NOERROR"
> FAIL
> ```

The 24th test case in handler_test.go TestServeDNS is the first one you added in the PR.

```
	// A TXT record does not exist but another record for the same FQDN does
 	{Case: test.Case{
 		Qname: "kubernetes.default.svc.cluster.local.", Qtype: dns.TypeTXT,
 		Rcode:  dns.RcodeSuccess,
 		Answer: []dns.RR{},
 	}},
```

The service `kubernetes.default.svc.cluster.local.` probably doesn't exist in the set of test data, so NXDOMAIN is expected.  You'll want to replace this query name with a name of a service that exists in the test data (e.g. from the first test case: `svc1.testns.svc.cluster.local.`).

**Comment by chrisohaver** [comment]
Regarding the new failure.  Note that NXDOMAIN responses are expected to have an authority section.  There should be some examples in other NXDOMAIN test cases.

Edit:  The same goes for "NODATA" responses (NOERROR + empty answer section) as in the failing test case - the SOA in the Authority section is expected for NODATA as well.  The SOA should be the same as in an NXDOMAIN response.

existing example: 

``` go
	// AAAA Service (with an existing A record, but no AAAA record)
	{Case: test.Case{
		Qname: "svc1.testns.svc.cluster.local.", Qtype: dns.TypeAAAA,
		Rcode: dns.RcodeSuccess,
		Ns: []dns.RR{
			test.SOA("cluster.local.	5	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1499347823 7200 1800 86400 5"),
		},
	}},
```

**Review by chrisohaver — CHANGES_REQUESTED** [review]
Looks good.  Please fix line 253 per the reviewdog comment in handler_test.go, and it should be good to merge.

**Comment by LAMRobinson** [comment]
Fab ! Sorry for the review churn here, really appreciate your help

**Review by chrisohaver — APPROVED** [review]
