### PR TITLE
plugin/ready: Reset list of readiness plugins on startup

### LINKED ISSUE #5481: Reloading with USR1 signal when server is not "ready" prevents the server to be able to become ready
**What happened**:

Single-node Kubernetes cluster boots, kube-apiserver and CoreDNS are starting (not exactly at the same time). Early at start CoreDNS config is updated and CoreDNS is reloaded via "pkill -e -USR1 coredns".

CoreDNS gets stuck in 'Still waiting on: "kubernetes"' state and DNS server never gets ready (readiness check always fails).

**What you expected to happen**:

After receiving USR1 signal, configuration should be reloaded and DNS server should be able to become ready.

**How to reproduce it (as minimally and precisely as possible)**:

1. CoreDNS should be waiting for "kubernetes" plugin to be ready (or perhaps any other plugin)
2. Send USR1 signal

**Anything else we need to know?**:

CoreDNS memory usage increases when it handles thousands of USR1 signals.

It looks like "plugins" list of "ready" plugin never gets emptied, but plugins are added when configuration is reloaded:
https://github.com/coredns/coredns/blob/390e88637e4307e37b494a70d58e9a2871c5f6bf/plugin/ready/setup.go#L27-L45
https://github.com/coredns/coredns/blob/390e88637e4307e37b494a70d58e9a2871c5f6bf/plugin/ready/ready.go#L69-L81

**Environment**:
Kubernetes 1.22.6

- the version of CoreDNS:
1.8.7
1.8.4
1.6.2

- Corefile:
```
    .:53 {
        log . {
          class denial error
        }
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /host-cfg/resolv.conf {
          prefer_udp
          max_fails 2
          expire 3s
          policy sequential
        }
        cache 30
        loop
        reload
        loadbalance
    }
```

- logs, if applicable:
```
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] SIGUSR1: Reloading
[INFO] Reloading
[WARNING] plugin/kubernetes: starting server with unsynced Kubernetes API
.:53
CoreDNS-1.8.4
linux/amd64, go1.16.4, 053c4d5
[INFO] plugin/ready: Still waiting on: "kubernetes,kubernetes"
[WARNING] plugin/kubernetes: starting server with unsynced Kubernetes API
[INFO] Reloading complete
[INFO] plugin/ready: Still waiting on: "kubernetes,kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes,kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
...
```
- OS (e.g: `cat /etc/os-release`):
coredns/coredns image

- Others:
n/a

### PR DESCRIPTION
**Pull request by chrisohaver**
Signed-off-by: Chris O'Haver <cohaver@infoblox.com>

### 1. Why is this pull request needed and what does it do?

When _ready_ starts, it adds all implementors of `readiness` to its list of plugins to check for readiness. But it never clears out the list, and accumulates references to readiness implementing plugins of prior configs on every reload (such as _kubernetes_).

Reloads can be triggered on demand, so this is a memory DoS concern.

Operationally, this could also cause readiness to perpetually fail if any of the prior instances cannot become ready (e.g. bad credentials in _kubernetes_ plugin).

### 2. Which issues (if any) are related?

#5481

### CODE REVIEW

File: test/reload_test.go [hunk 1]
```diff
@@ -327,4 +332,62 @@ func TestMetricsAvailableAfterReloadAndFailedReload(t *testing.T) {
 	// verify that metrics have not been pushed
 }
 
+
+// TestReloadUnreadyPlugin tests that the ready plugin properly resets the list of readiness implementors during a reload.
+// If it fails to do so, ready will respond with duplicate plugin names after a reload (e.g. in this test "unready,unready").
+func TestReloadUnreadyPlugin(t *testing.T) {
+	// Add/Register a perpetually unready plugin
+	dnsserver.Directives = append( []string{"unready"}, dnsserver.Directives...)
```
Comment (Tantalor93) [inline test/reload_test.go]:
```suggestion
	dnsserver.Directives = append([]string{"unready"}, dnsserver.Directives...)
```

File: test/reload_test.go [hunk 2]
```diff
@@ -327,4 +332,62 @@ func TestMetricsAvailableAfterReloadAndFailedReload(t *testing.T) {
 	// verify that metrics have not been pushed
 }
 
+
```
Comment (Tantalor93) [inline test/reload_test.go]: as suggested please remove redundant new line

File: test/reload_test.go [hunk 3]
```diff
@@ -327,4 +332,62 @@ func TestMetricsAvailableAfterReloadAndFailedReload(t *testing.T) {
...
+	}
+
+	c1.Stop()
+}
+
+type unready struct {
+	next plugin.Handler
+}
+
+func (u *unready) Ready() bool{return false}
```
Comment (Tantalor93) [inline test/reload_test.go]:
```suggestion
func (u *unready) Ready() bool{ return false }
```

File: test/reload_test.go [hunk 4]
```diff
@@ -327,4 +332,62 @@ func TestMetricsAvailableAfterReloadAndFailedReload(t *testing.T) {
...
+
+func (u *unready) Name() string {return "unready"}
```
Comment (Tantalor93) [inline test/reload_test.go]:
```suggestion
func (u *unready) Name() string { return "unready" }
```

**Review by Tantalor93 — COMMENTED** [review]
just minor comments also noted by reviewdog, otherwise LGTM

**Review by Tantalor93 — APPROVED** [review]
